//! JSON-RPC request/response plumbing over transport streams, mirroring
//! `chuk_mcp.protocol.messages.send_message`.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;

use serde_json::Value;
use tokio::sync::{mpsc, Mutex, Notify};

use crate::protocol::json_rpc::{create_request, JsonRpcMessage, ProgressToken, RequestId};
use crate::protocol::messages::method::MessageMethod;
use crate::protocol::messages::notifications::send_cancelled_notification;
use crate::protocol::types::errors::{get_error_message, McpError};

/// Stream of incoming messages from a transport.
///
/// Wrapped in `Arc<Mutex<..>>` so a client can hold it across sequential
/// requests, matching how the Python package shares its anyio memory streams.
pub type ReadStream = Arc<Mutex<mpsc::Receiver<JsonRpcMessage>>>;

/// Stream of outgoing messages to a transport.
pub type WriteStream = mpsc::Sender<JsonRpcMessage>;

/// Create a connected (write, read) stream pair with the given buffer size.
/// Transports use this to build their public stream endpoints.
pub fn message_channel(buffer: usize) -> (mpsc::Sender<JsonRpcMessage>, ReadStream) {
    let (tx, rx) = mpsc::channel(buffer);
    (tx, Arc::new(Mutex::new(rx)))
}

/// Token to enable request cancellation.
#[derive(Debug, Clone, Default)]
pub struct CancellationToken {
    inner: Arc<CancellationInner>,
}

#[derive(Debug, Default)]
struct CancellationInner {
    cancelled: AtomicBool,
    notify: Notify,
}

impl CancellationToken {
    pub fn new() -> Self {
        Self::default()
    }

    /// Mark this token as cancelled and wake any waiters.
    pub fn cancel(&self) {
        self.inner.cancelled.store(true, Ordering::SeqCst);
        self.inner.notify.notify_waiters();
    }

    /// Check if cancellation was requested.
    pub fn is_cancelled(&self) -> bool {
        self.inner.cancelled.load(Ordering::SeqCst)
    }

    /// Resolve when the token is cancelled.
    pub async fn cancelled(&self) {
        while !self.is_cancelled() {
            self.inner.notify.notified().await;
        }
    }
}

/// Callback invoked with `(progress, total, message)` on progress notifications.
pub type ProgressCallback = Arc<dyn Fn(f64, Option<f64>, Option<String>) + Send + Sync>;

/// Options for [`send_message_with_options`].
#[derive(Clone, Default)]
pub struct SendMessageOptions {
    /// Timeout for the response. Defaults to 60 seconds.
    pub timeout: Option<Duration>,
    /// Custom request id; autogenerated UUID if `None`.
    pub message_id: Option<RequestId>,
    /// Token to enable request cancellation.
    pub cancellation_token: Option<CancellationToken>,
    /// Callback for `notifications/progress` updates tied to this request.
    pub progress_callback: Option<ProgressCallback>,
}

/// Default request timeout (matches the Python `timeout: float = 60.0`).
pub const DEFAULT_TIMEOUT: Duration = Duration::from_secs(60);

/// Send a JSON-RPC request and await the matching response.
///
/// Errors are surfaced immediately without retries; a JSON-RPC error response
/// becomes [`McpError::Retryable`] or [`McpError::NonRetryable`] based on its
/// code. Non-matching messages received while waiting are skipped.
pub async fn send_message(
    read_stream: &ReadStream,
    write_stream: &WriteStream,
    method: &str,
    params: Option<Value>,
) -> Result<Value, McpError> {
    send_message_with_options(
        read_stream,
        write_stream,
        method,
        params,
        SendMessageOptions::default(),
    )
    .await
}

/// [`send_message`] with explicit timeout, id, cancellation, and progress options.
pub async fn send_message_with_options(
    read_stream: &ReadStream,
    write_stream: &WriteStream,
    method: &str,
    params: Option<Value>,
    options: SendMessageOptions,
) -> Result<Value, McpError> {
    let timeout = options.timeout.unwrap_or(DEFAULT_TIMEOUT);

    // Generate a progress token when a callback is provided; create_request
    // stores it under params._meta.progressToken.
    let progress_token: Option<ProgressToken> = options
        .progress_callback
        .is_some()
        .then(|| RequestId::Str(uuid::Uuid::new_v4().to_string()));

    let request = create_request(method, params, options.message_id, progress_token.clone());
    let req_id = request.id.clone();

    if let Some(token) = &options.cancellation_token {
        if token.is_cancelled() {
            return Err(cancel_and_report(write_stream, &req_id).await);
        }
    }

    tracing::debug!("[send_message] sending {method}");
    write_stream
        .send(JsonRpcMessage::Request(request))
        .await
        .map_err(|_| McpError::Transport("write stream closed".into()))?;

    match tokio::time::timeout(
        timeout,
        await_response(
            read_stream,
            &req_id,
            options.cancellation_token.as_ref(),
            progress_token.as_ref(),
            options.progress_callback.as_ref(),
            write_stream,
        ),
    )
    .await
    {
        Ok(result) => result,
        Err(_) => Err(McpError::Timeout(timeout)),
    }
}

/// Send a cancellation notification for `req_id` and return the Cancelled error.
async fn cancel_and_report(write_stream: &WriteStream, req_id: &RequestId) -> McpError {
    if let Err(e) =
        send_cancelled_notification(write_stream, req_id.clone(), Some("Cancelled by client")).await
    {
        tracing::error!("Failed to send cancellation notification: {e}");
    }
    McpError::Cancelled(req_id.to_string())
}

/// Loop until a response matching `req_id` arrives, handling progress
/// notifications and cancellation along the way.
async fn await_response(
    read_stream: &ReadStream,
    req_id: &RequestId,
    cancellation_token: Option<&CancellationToken>,
    progress_token: Option<&ProgressToken>,
    progress_callback: Option<&ProgressCallback>,
    write_stream: &WriteStream,
) -> Result<Value, McpError> {
    let mut receiver = read_stream.lock().await;

    loop {
        let msg = tokio::select! {
            msg = receiver.recv() => msg.ok_or_else(|| {
                McpError::Transport("read stream closed while awaiting response".into())
            })?,
            _ = async {
                match cancellation_token {
                    Some(token) => token.cancelled().await,
                    None => std::future::pending().await,
                }
            } => {
                return Err(cancel_and_report(write_stream, req_id).await);
            }
        };

        // Progress notifications tied to this request are reported and skipped.
        if let (Some(token), Some(callback)) = (progress_token, progress_callback) {
            if msg.method() == Some(MessageMethod::NOTIFICATION_PROGRESS) {
                let params = msg.params().cloned().unwrap_or(Value::Null);
                let matches = params
                    .get("progressToken")
                    .map(|t| {
                        serde_json::from_value::<ProgressToken>(t.clone())
                            .map(|t| &t == token)
                            .unwrap_or(false)
                    })
                    .unwrap_or(false);
                if matches {
                    callback(
                        params
                            .get("progress")
                            .and_then(Value::as_f64)
                            .unwrap_or(0.0),
                        params.get("total").and_then(Value::as_f64),
                        params
                            .get("message")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                    );
                    continue;
                }
            }
        }

        // Filter by matching id.
        if msg.id() != Some(req_id) {
            tracing::debug!("[send_message] skip unmatched id={:?}", msg.id());
            continue;
        }

        return process_response(msg);
    }
}

/// Turn a matched response into its result value or a typed error.
fn process_response(msg: JsonRpcMessage) -> Result<Value, McpError> {
    match msg {
        JsonRpcMessage::Error(err) => {
            let code = err.error.code;
            let message = format!(
                "JSON-RPC Error: {} (code: {code})",
                if err.error.message.is_empty() {
                    get_error_message(code)
                } else {
                    err.error.message.clone()
                }
            );
            Err(McpError::from_json_rpc(code, message, err.error.data))
        }
        JsonRpcMessage::Response(resp) => Ok(resp.result),
        other => Ok(other.to_value()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::json_rpc::{create_error_response, create_response};
    use serde_json::json;

    /// Build a fake transport: returns (read_stream for client, write end to
    /// inject server messages, and the receiver capturing client sends).
    fn fake_transport() -> (
        ReadStream,
        mpsc::Sender<JsonRpcMessage>,
        WriteStream,
        mpsc::Receiver<JsonRpcMessage>,
    ) {
        let (incoming_tx, incoming) = message_channel(16);
        let (outgoing_tx, outgoing_rx) = mpsc::channel(16);
        (incoming, incoming_tx, outgoing_tx, outgoing_rx)
    }

    #[tokio::test]
    async fn matches_response_by_id() {
        let (read, inject, write, mut sent) = fake_transport();

        let client = tokio::spawn(async move { send_message(&read, &write, "ping", None).await });

        let request = sent.recv().await.unwrap();
        let id = request.id().unwrap().clone();

        // Unmatched response first: should be skipped.
        inject
            .send(JsonRpcMessage::Response(create_response(
                "other".into(),
                Some(json!({"wrong": true})),
            )))
            .await
            .unwrap();
        inject
            .send(JsonRpcMessage::Response(create_response(
                id,
                Some(json!({"ok": true})),
            )))
            .await
            .unwrap();

        assert_eq!(client.await.unwrap().unwrap(), json!({"ok": true}));
    }

    #[tokio::test]
    async fn error_response_classified() {
        let (read, inject, write, mut sent) = fake_transport();

        let client =
            tokio::spawn(async move { send_message(&read, &write, "tools/call", None).await });

        let id = sent.recv().await.unwrap().id().unwrap().clone();
        inject
            .send(JsonRpcMessage::Error(create_error_response(
                id,
                crate::protocol::types::errors::METHOD_NOT_FOUND,
                "nope",
                None,
            )))
            .await
            .unwrap();

        let err = client.await.unwrap().unwrap_err();
        assert!(!err.is_retryable());
    }

    #[tokio::test]
    async fn times_out() {
        let (read, _inject, write, _sent) = fake_transport();
        let result = send_message_with_options(
            &read,
            &write,
            "ping",
            None,
            SendMessageOptions {
                timeout: Some(Duration::from_millis(50)),
                ..Default::default()
            },
        )
        .await;
        assert!(matches!(result, Err(McpError::Timeout(_))));
    }

    #[tokio::test]
    async fn cancellation_sends_notification() {
        let (read, _inject, write, mut sent) = fake_transport();
        let token = CancellationToken::new();
        let token2 = token.clone();

        let client = tokio::spawn(async move {
            send_message_with_options(
                &read,
                &write,
                "tools/call",
                None,
                SendMessageOptions {
                    cancellation_token: Some(token2),
                    ..Default::default()
                },
            )
            .await
        });

        let _request = sent.recv().await.unwrap();
        token.cancel();

        let result = client.await.unwrap();
        assert!(matches!(result, Err(McpError::Cancelled(_))));

        let cancel_msg = sent.recv().await.unwrap();
        assert_eq!(
            cancel_msg.method(),
            Some(MessageMethod::NOTIFICATION_CANCELLED)
        );
    }

    #[tokio::test]
    async fn progress_notifications_reported() {
        let (read, inject, write, mut sent) = fake_transport();
        let progress_log = Arc::new(std::sync::Mutex::new(Vec::new()));
        let log2 = progress_log.clone();

        let client = tokio::spawn(async move {
            send_message_with_options(
                &read,
                &write,
                "tools/call",
                None,
                SendMessageOptions {
                    progress_callback: Some(Arc::new(move |p, t, m| {
                        log2.lock().unwrap().push((p, t, m));
                    })),
                    ..Default::default()
                },
            )
            .await
        });

        let request = sent.recv().await.unwrap();
        let id = request.id().unwrap().clone();
        let token = request.params().unwrap()["_meta"]["progressToken"].clone();

        inject
            .send(JsonRpcMessage::Notification(
                crate::protocol::json_rpc::create_notification(
                    MessageMethod::NOTIFICATION_PROGRESS,
                    Some(json!({"progressToken": token, "progress": 0.5, "total": 1.0})),
                ),
            ))
            .await
            .unwrap();
        inject
            .send(JsonRpcMessage::Response(create_response(id, None)))
            .await
            .unwrap();

        client.await.unwrap().unwrap();
        assert_eq!(progress_log.lock().unwrap().len(), 1);
    }
}
